{% set name = "ydata-synthetic" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-synthetic-{{ version }}.tar.gz
  sha256: 9c1ebcc5275106abf1cb3da4703e70df0a7c0d6c3329ab1182529fd1a905eac2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - requests >=2.24.0,<2.31
    - pandas >=1.3.0,<2.1
    - numpy >=1.21.0,<1.24.0
    - scikit-learn >=1.0.2,<1.3.0
    - matplotlib-base >=3.5.0,<3.7.0
    - tensorflow >=2.8.0
    - tensorflow-probability >=0.16.0
    - easydict >=1.9
    - pmlb >=1.0.1
    - tqdm <5.0
    - typeguard >=2.13.0,<2.14.0
    - pytest >=6.2.0

test:
  imports:
    - ydata_synthetic
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-synthetic
  summary: Synthetic data generation methods with different synthetization methods.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
