{% set name = "ydata-synthetic" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-synthetic-{{ version }}.tar.gz
  sha256: b6ab644ccd2df3ec3130e9cdc7d88d79ccfaedb0e3cccaab3c5386bbfae2a6a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.8,<3.11
    - requests >=2.24.0,<2.29
    - pandas >=1.5.0,<1.6.0
    - numpy >=1.23.0,<1.24.0
    - scikit-learn >=1.2.0,<1.3.0
    - matplotlib-base >=3.6.0,<3.7.0
    - tensorflow ==2.11.0
    - tensorflow-probability ==0.19.0    
    - easydict >=1.9
    - pmlb >=1.0.1
    - tqdm <5.0
    - typeguard >=2.13.0,<2.14.0
    - pytest >=6.2.0,<6.3.0

test:
  imports:
    - ydata_synthetic
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-synthetic
  summary: Synthetic data generation methods with different synthetization methods.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
